### ISSUE TITLE
默认安装失败

### ISSUE THREAD

**Issue by liuxyon** [Jrohy/trojan#353]
trojan-go 启动不正常. 应该配置有错误.

`[INFO]  2020/12/30 01:08:43 trojan-go v0.8.2 initializing
[WARN]  2020/12/30 01:08:43 empty tls fallback port
[FATAL] 2020/12/30 01:08:43 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
trojan.service: Main process exited, code=exited, status=1/FAILURE
trojan.service: Failed with result 'exit-code'.
trojan.service: Scheduled restart job, restart counter is at 96`

**Comment by Jrohy** [comment]
证书申请成功了么，有没有自己修改配置文件

**Comment by liuxyon** [comment]
我没有修改,安装好几遍,链接不通我才看日志有这个.  我用其它一键脚本安装是通的.

**Comment by Jrohy** [comment]
检查下配置文件有没问题，默认安装应该是trojan才对，是有切换过了吗

**Comment by liuxyon** [comment]
有切换, 主要是都不通,能不能灵活读取已有torjan服务,这样比较灵活.

**Comment by Jrohy** [comment]
不能的，最好是干净的vps来安装

**Comment by liuxyon** [comment]
可是安装你的不通,安装过程中也没有提示任何错误, web界面都能打开.

**Comment by Jrohy** [comment]
web界面通过https能访问不

**Comment by mzt1988** [comment]
[Fri Mar 12 06:17:12 UTC 2021] Installing from online archive.
[Fri Mar 12 06:17:12 UTC 2021] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Fri Mar 12 06:17:13 UTC 2021] Extracting master.tar.gz
[Fri Mar 12 06:17:14 UTC 2021] It is recommended to install crontab first. try to install 'cron, crontab, crontabs or vixie-cron'.
[Fri Mar 12 06:17:14 UTC 2021] We need to set cron job to renew the certs automatically.
[Fri Mar 12 06:17:14 UTC 2021] Otherwise, your certs will not be able to be renewed automatically.
[Fri Mar 12 06:17:14 UTC 2021] Please add '--force' and try install again to go without crontab.
[Fri Mar 12 06:17:14 UTC 2021] ./acme.sh --install --force
[Fri Mar 12 06:17:14 UTC 2021] Pre-check failed, can not install.
Failed to stop trojan-web.service: Access denied
See system logs and 'systemctl status trojan-web.service' for details.
bash: /root/.acme.sh/acme.sh: Permission denied
open /usr/local/etc/trojan/config.json: permission denied
Failed to restart trojan.service: Access denied
See system logs and 'systemctl status trojan.service' for details.
重启trojan失败!
Failed to restart trojan-web.service: Access denied
See system logs and 'systemctl status trojan-web.service' for details.
